<?php  
return [
    [
        'name' => 'leonardo',
        'email' => 'leonardo@buymore.com',
        'password' => 'pozzan',
        'image' => 'https://avatars.githubusercontent.com/u/108693204?v=4',
        'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam, tempora enim pariatur saepe illo impedit?',
        'qualification' => 'CEO, Full Stack Developer',
        'flag' => 'CEO',
        'github' => 'https://github.com/leonardopozzan',
    ],
    [
        'name' => 'valentina',
        'email' => 'valentina@buymore.com',
        'password' => 'zussino',
        'image' => 'https://avatars.githubusercontent.com/u/107954392?v=4
        ',
        'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam, tempora enim pariatur saepe illo impedit?',
        'qualification' => 'COO, Full Stack Developer',
        'flag' => 'COO',
        'github' => 'https://github.com/ValentinaZussino',
    ],
    [
        'name' => 'alessio',
        'email' => 'alessio@buymore.com',
        'password' => 'bonadonna',
        'image' => 'https://avatars.githubusercontent.com/u/48909804?v=4',
        'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam, tempora enim pariatur saepe illo impedit?',
        'qualification' => 'Project Manager, Full Stack Developer',
        'flag' => 'Project Manager',
        'github' => 'https://github.com/AlessioBonadonna',
    ],
    [
        'name' => 'lorenzo',
        'email' => 'lorenzo@buymore.com',
        'password' => 'castiglion',
        'image' => 'https://avatars.githubusercontent.com/u/111997828?v=4',
        'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam, tempora enim pariatur saepe illo impedit?',
        'qualification' => 'Chief Designer, Full Stack Developer',
        'flag' => 'Chief Designer',
        'github' => 'https://github.com/LorenzoCastiglion',
    ],
    [
        'name' => 'riccardo',
        'email' => 'riccardo@buymore.com',
        'password' => 'pellegrino',
        'image' => 'https://avatars.githubusercontent.com/u/64532705?v=4',
        'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam, tempora enim pariatur saepe illo impedit?',
        'qualification' => 'CTO, Full Stack Developer',
        'flag' => 'CTO',
        'github' => 'https://github.com/RiccardoPellegrino',
    ],
]
?>